# PromptSRC: Prompting with Self-regularizing constraints
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 4
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.0035
  MAX_EPOCH: 10
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 10

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TEST:
  FINAL_MODEL: "best_val"
  NO_TEST: False

TRAINER:
  PROMPTKD:
    N_CTX_VISION: 4
    N_CTX_TEXT: 4
    CTX_INIT: "a photo of a"
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 9
    PROMPT_DEPTH_TEXT: 9
    TEACHER_NAME: "ViT-L/14"
    PROJECT_LAYER: 2
    CE_WEIGHT: 0.0
    KD_WEIGHT: 1.0

SPLE:
  SPLE_TRAINER:
    SPLE_INIT: True
    SPLE_BASE_TRAIN: True
  BACK_CKPT_PATH: "output/PromptKD/base2new/train_base/caltech101/1_PromptKD_baseline/vit_b16_c2_ep20_batch32_4+4ctx/seed1"
  BACK_CKPT_EPOCH: 10
  INFER_TOPK: 8
  INFER_NONREPEAT: True
  PIC_LIB: "DATA/SPLE_database/SPLE_Caltech101.json"
  LOSS_KD_WEIGHT: 0.5
  STACK:
    MODE: "loop+converse"
    WEIGHT: 0.2
    LOOP_DEPTH: 0